In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [8]:
df = pd.read_csv('/content/qoute_dataset.csv')

In [9]:
df.head()

                                               quote           Author
0  “The world as we have created it is a process ...  Albert Einstein
1  “It is our choices, Harry, that show what we t...     J.K. Rowling
2  “There are only two ways to live your life. On...  Albert Einstein
3  “The person, be it gentleman or lady, who has ...      Jane Austen
4  “Imperfection is beauty, madness is genius and...   Marilyn Monroe

In [10]:
df['quote'][0]

'“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”'

In [11]:
df.shape

(3038, 2)

In [12]:
quotes = df['quote']
quotes.head()

0    “The world as we have created it is a process ...
1    “It is our choices, Harry, that show what we t...
2    “There are only two ways to live your life. On...
3    “The person, be it gentleman or lady, who has ...
4    “Imperfection is beauty, madness is genius and...
Name: quote, dtype: object

In [ ]:
quotes = df['quote'].str.lower()

In [ ]:
import string
translator = str.maketrans('', '', string.punctuation)
quotes = quotes.apply(lambda x: x.translate(translator))

In [13]:
quotes.head()

0    “The world as we have created it is a process ...
1    “It is our choices, Harry, that show what we t...
2    “There are only two ways to live your life. On...
3    “The person, be it gentleman or lady, who has ...
4    “Imperfection is beauty, madness is genius and...
Name: quote, dtype: object

In [14]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [15]:
vocab_size = 10000
tokenizer = Tokenizer(num_words=vocab_size)
tokenizer.fit_on_texts(quotes)

In [16]:
word_index = tokenizer.word_index
print(len(word_index))
list(word_index.items())[:10]

8213

[('the', 1),
 ('you', 2),
 ('to', 3),
 ('and', 4),
 ('a', 5),
 ('i', 6),
 ('is', 7),
 ('of', 8),
 ('that', 9),
 ('it', 10)]

In [17]:
sequences = tokenizer.texts_to_sequences(quotes)

In [18]:
for i in range(3):
    print(quotes[i])

“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”
“It is our choices, Harry, that show what we truly are, far more than our abilities.”
“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”

In [19]:
for i in range(3):
    print(sequences[i])

[732, 61, 30, 19, 17, 901, 10, 7, 5, 1188, 8, 71, 290, 10, 149, 12, 835, 103, 776, 71, 290, 136]
[977, 7, 71, 902, 388, 9, 431, 21, 19, 479, 14, 299, 51, 55, 71, 2545, 136]
[1384, 14, 53, 203, 700, 3, 80, 15, 37, 36, 7, 30, 300, 92, 7, 5, 1073, 1, 104, 7, 30, 300, 126, 7, 5, 1073, 136]

In [20]:
X = []
y = []

for seq in sequences:
    for i in range(1, len(seq)):
        input_seq = seq[:i]
        output_seq = seq[i]
        X.append(input_seq)
        y.append(output_seq)

In [21]:
len(X)

86549

In [22]:
len(y)

86549

In [23]:
max_len = max(len(x) for x in X)
print(max_len)

748

In [24]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
X_padded = pad_sequences(X, maxlen=max_len, padding='pre')

In [25]:
y = np.array(y)

In [26]:
X_padded.shape

(86549, 748)

In [27]:
from tensorflow.keras.utils import to_categorical
y_one_hot = to_categorical(y, num_classes=vocab_size)

In [28]:
y_one_hot.shape

(86549, 10000)

In [29]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, LSTM, Dense

In [30]:
embedding_dim = 50
rnn_units = 128

In [31]:
rnn_model = Sequential()
rnn_model.add(Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_len))
rnn_model.add(SimpleRNN(units=rnn_units))
rnn_model.add(Dense(units=vocab_size, activation='softmax'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [32]:
rnn_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [33]:
rnn_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [34]:
lstm_model = Sequential()
lstm_model.add(Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_len))
lstm_model.add(LSTM(units=rnn_units))
lstm_model.add(Dense(units=vocab_size, activation='softmax'))

In [35]:
lstm_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [36]:
lstm_model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [37]:
epochs = 10
batch_size = 128

In [38]:
history_rnn = rnn_model.fit(
    X_padded, y_one_hot,
    epochs=epochs,
    batch_size=batch_size,
    validation_split=0.1
)

Epoch 1/10
609/609 ━━━━━━━━━━━━━━━━━━━━ 48s 70ms/step - accuracy: 0.0444 - loss: 6.6680 - val_accuracy: 0.0608 - val_loss: 6.5181
Epoch 2/10
609/609 ━━━━━━━━━━━━━━━━━━━━ 39s 64ms/step - accuracy: 0.0731 - loss: 6.1641 - val_accuracy: 0.0821 - val_loss: 6.3656
Epoch 3/10
609/609 ━━━━━━━━━━━━━━━━━━━━ 39s 64ms/step - accuracy: 0.0964 - loss: 5.8269 - val_accuracy: 0.0968 - val_loss: 6.2566
Epoch 4/10
609/609 ━━━━━━━━━━━━━━━━━━━━ 39s 64ms/step - accuracy: 0.1124 - loss: 5.5587 - val_accuracy: 0.1002 - val_loss: 6.2494
Epoch 5/10
609/609 ━━━━━━━━━━━━━━━━━━━━ 39s 64ms/step - accuracy: 0.1248 - loss: 5.3256 - val_accuracy: 0.1051 - val_loss: 6.2768
Epoch 6/10
609/609 ━━━━━━━━━━━━━━━━━━━━ 41s 64ms/step - accuracy: 0.1357 - loss: 5.1142 - val_accuracy: 0.1101 - val_loss: 6.3040
Epoch 7/10
609/609 ━━━━━━━━━━━━━━━━━━━━ 39s 63ms/step - accuracy: 0.1461 - loss: 4.9148 - val_accuracy: 0.1092 - val_loss: 6.3595
Epoch 8/10
609/609 ━━━━━━━━━━━━━━━━━━━━ 39s 63ms/step - accuracy: 0.1584 - loss: 4.7267 - val_accuracy: 0.1105 - val_loss: 6.4205
Epoch 9/10
609/609 ━━━━━━━━━━━━━━━━━━━━ 39s 64ms/step - accuracy: 0.1748 - loss: 4.5442 - val_accuracy: 0.1107 - val_loss: 6.4827
Epoch 10/10
609/609 ━━━━━━━━━━━━━━━━━━━━ 41s 64ms/step - accuracy: 0.1915 - loss: 4.3705 - val_accuracy: 0.1086 - val_loss: 6.5409

In [39]:
epochs = 100
batch_size = 128
history_lstm = lstm_model.fit(
X_padded,
y_one_hot,
epochs=epochs,
batch_size=batch_size,
validation_split=0.1
)

Epoch 1/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 41s 57ms/step - accuracy: 0.0392 - loss: 6.7085 - val_accuracy: 0.0452 - val_loss: 6.6502
Epoch 2/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.0597 - loss: 6.2641 - val_accuracy: 0.0702 - val_loss: 6.5012
Epoch 3/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.0827 - loss: 6.0042 - val_accuracy: 0.0892 - val_loss: 6.4014
Epoch 4/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.0987 - loss: 5.8011 - val_accuracy: 0.0967 - val_loss: 6.3636
Epoch 5/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.1092 - loss: 5.6290 - val_accuracy: 0.1003 - val_loss: 6.3534
Epoch 6/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.1190 - loss: 5.4600 - val_accuracy: 0.1028 - val_loss: 6.3558
Epoch 7/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.1281 - loss: 5.3011 - val_accuracy: 0.1062 - val_loss: 6.3750
Epoch 8/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 41s 54ms/step - accuracy: 0.1364 - loss: 5.1530 - val_accuracy: 0.1068 - val_loss: 6.3805
Epoch 9/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.1442 - loss: 5.0123 - val_accuracy: 0.1087 - val_loss: 6.4315
Epoch 10/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 41s 54ms/step - accuracy: 0.1522 - loss: 4.8783 - val_accuracy: 0.1095 - val_loss: 6.4740
Epoch 11/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.1582 - loss: 4.7470 - val_accuracy: 0.1123 - val_loss: 6.5179
Epoch 12/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.1662 - loss: 4.6188 - val_accuracy: 0.1137 - val_loss: 6.5712
Epoch 13/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.1751 - loss: 4.4944 - val_accuracy: 0.1114 - val_loss: 6.6334
Epoch 14/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.1843 - loss: 4.3726 - val_accuracy: 0.1163 - val_loss: 6.7008
Epoch 15/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.1956 - loss: 4.2553 - val_accuracy: 0.1147 - val_loss: 6.7653
Epoch 16/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.2084 - loss: 4.1410 - val_accuracy: 0.1150 - val_loss: 6.8435
Epoch 17/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.2222 - loss: 4.0322 - val_accuracy: 0.1154 - val_loss: 6.9179
Epoch 18/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.2358 - loss: 3.9278 - val_accuracy: 0.1140 - val_loss: 6.9874
Epoch 19/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.2500 - loss: 3.8278 - val_accuracy: 0.1154 - val_loss: 7.0681
Epoch 20/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.2632 - loss: 3.7361 - val_accuracy: 0.1109 - val_loss: 7.1618
Epoch 21/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.2755 - loss: 3.6473 - val_accuracy: 0.1122 - val_loss: 7.2320
Epoch 22/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.2888 - loss: 3.5644 - val_accuracy: 0.1113 - val_loss: 7.3102
Epoch 23/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.3000 - loss: 3.4863 - val_accuracy: 0.1088 - val_loss: 7.3993
Epoch 24/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.3133 - loss: 3.4118 - val_accuracy: 0.1070 - val_loss: 7.4667
Epoch 25/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.3238 - loss: 3.3407 - val_accuracy: 0.1066 - val_loss: 7.5513
Epoch 26/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.3354 - loss: 3.2736 - val_accuracy: 0.1056 - val_loss: 7.6152
Epoch 27/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.3461 - loss: 3.2088 - val_accuracy: 0.1018 - val_loss: 7.7019
Epoch 28/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.3560 - loss: 3.1459 - val_accuracy: 0.1048 - val_loss: 7.7624
Epoch 29/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.3652 - loss: 3.0863 - val_accuracy: 0.1046 - val_loss: 7.8213
Epoch 30/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 42s 56ms/step - accuracy: 0.3766 - loss: 3.0277 - val_accuracy: 0.1039 - val_loss: 7.8942
Epoch 31/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.3856 - loss: 2.9720 - val_accuracy: 0.1046 - val_loss: 7.9653
Epoch 32/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 34s 55ms/step - accuracy: 0.3940 - loss: 2.9191 - val_accuracy: 0.1018 - val_loss: 8.0326
Epoch 33/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.4045 - loss: 2.8651 - val_accuracy: 0.1011 - val_loss: 8.0915
Epoch 34/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 34s 55ms/step - accuracy: 0.4135 - loss: 2.8155 - val_accuracy: 0.0988 - val_loss: 8.1664
Epoch 35/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 42s 57ms/step - accuracy: 0.4214 - loss: 2.7668 - val_accuracy: 0.1004 - val_loss: 8.2439
Epoch 36/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.4287 - loss: 2.7182 - val_accuracy: 0.0981 - val_loss: 8.3168
Epoch 37/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.4389 - loss: 2.6731 - val_accuracy: 0.0982 - val_loss: 8.3710
Epoch 38/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.4461 - loss: 2.6272 - val_accuracy: 0.0987 - val_loss: 8.4357
Epoch 39/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 34s 55ms/step - accuracy: 0.4541 - loss: 2.5862 - val_accuracy: 0.0986 - val_loss: 8.5061
Epoch 40/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.4614 - loss: 2.5417 - val_accuracy: 0.0980 - val_loss: 8.5577
Epoch 41/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.4702 - loss: 2.5002 - val_accuracy: 0.0959 - val_loss: 8.6147
Epoch 42/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 34s 55ms/step - accuracy: 0.4757 - loss: 2.4607 - val_accuracy: 0.0937 - val_loss: 8.6931
Epoch 43/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.4851 - loss: 2.4220 - val_accuracy: 0.0961 - val_loss: 8.7455
Epoch 44/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 35s 57ms/step - accuracy: 0.4898 - loss: 2.3836 - val_accuracy: 0.0954 - val_loss: 8.8167
Epoch 45/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.4977 - loss: 2.3459 - val_accuracy: 0.0936 - val_loss: 8.8727
Epoch 46/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.5039 - loss: 2.3105 - val_accuracy: 0.0929 - val_loss: 8.9324
Epoch 47/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.5110 - loss: 2.2755 - val_accuracy: 0.0930 - val_loss: 8.9934
Epoch 48/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5172 - loss: 2.2424 - val_accuracy: 0.0904 - val_loss: 9.0456
Epoch 49/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 34s 55ms/step - accuracy: 0.5242 - loss: 2.2083 - val_accuracy: 0.0922 - val_loss: 9.1133
Epoch 50/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 34s 55ms/step - accuracy: 0.5307 - loss: 2.1762 - val_accuracy: 0.0901 - val_loss: 9.1832
Epoch 51/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 34s 55ms/step - accuracy: 0.5375 - loss: 2.1445 - val_accuracy: 0.0943 - val_loss: 9.2283
Epoch 52/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 42s 56ms/step - accuracy: 0.5438 - loss: 2.1130 - val_accuracy: 0.0891 - val_loss: 9.2826
Epoch 53/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.5483 - loss: 2.0837 - val_accuracy: 0.0878 - val_loss: 9.3594
Epoch 54/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 34s 55ms/step - accuracy: 0.5547 - loss: 2.0542 - val_accuracy: 0.0890 - val_loss: 9.4220
Epoch 55/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 34s 55ms/step - accuracy: 0.5610 - loss: 2.0249 - val_accuracy: 0.0882 - val_loss: 9.4664
Epoch 56/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5662 - loss: 1.9961 - val_accuracy: 0.0891 - val_loss: 9.5223
Epoch 57/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 34s 55ms/step - accuracy: 0.5725 - loss: 1.9689 - val_accuracy: 0.0875 - val_loss: 9.5878
Epoch 58/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.5786 - loss: 1.9408 - val_accuracy: 0.0863 - val_loss: 9.6540
Epoch 59/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5828 - loss: 1.9159 - val_accuracy: 0.0885 - val_loss: 9.6937
Epoch 60/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5881 - loss: 1.8915 - val_accuracy: 0.0886 - val_loss: 9.7398
Epoch 61/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.5929 - loss: 1.8658 - val_accuracy: 0.0858 - val_loss: 9.8217
Epoch 62/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5977 - loss: 1.8412 - val_accuracy: 0.0868 - val_loss: 9.8857
Epoch 63/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 41s 54ms/step - accuracy: 0.6027 - loss: 1.8163 - val_accuracy: 0.0876 - val_loss: 9.9157
Epoch 64/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6076 - loss: 1.7925 - val_accuracy: 0.0873 - val_loss: 9.9714
Epoch 65/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.6115 - loss: 1.7703 - val_accuracy: 0.0875 - val_loss: 10.0599
Epoch 66/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 41s 55ms/step - accuracy: 0.6180 - loss: 1.7478 - val_accuracy: 0.0842 - val_loss: 10.0912
Epoch 67/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 41s 55ms/step - accuracy: 0.6228 - loss: 1.7257 - val_accuracy: 0.0840 - val_loss: 10.1234
Epoch 68/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6264 - loss: 1.7051 - val_accuracy: 0.0846 - val_loss: 10.1930
Epoch 69/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.6315 - loss: 1.6837 - val_accuracy: 0.0849 - val_loss: 10.2331
Epoch 70/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6349 - loss: 1.6620 - val_accuracy: 0.0803 - val_loss: 10.3083
Epoch 71/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.6390 - loss: 1.6419 - val_accuracy: 0.0840 - val_loss: 10.3453
Epoch 72/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.6440 - loss: 1.6211 - val_accuracy: 0.0843 - val_loss: 10.4107
Epoch 73/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 34s 55ms/step - accuracy: 0.6488 - loss: 1.6021 - val_accuracy: 0.0821 - val_loss: 10.4478
Epoch 74/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.6527 - loss: 1.5818 - val_accuracy: 0.0825 - val_loss: 10.4995
Epoch 75/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.6540 - loss: 1.5662 - val_accuracy: 0.0828 - val_loss: 10.5631
Epoch 76/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6606 - loss: 1.5468 - val_accuracy: 0.0793 - val_loss: 10.5952
Epoch 77/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6636 - loss: 1.5282 - val_accuracy: 0.0795 - val_loss: 10.6590
Epoch 78/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6683 - loss: 1.5107 - val_accuracy: 0.0816 - val_loss: 10.7155
Epoch 79/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6710 - loss: 1.4934 - val_accuracy: 0.0800 - val_loss: 10.7670
Epoch 80/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6752 - loss: 1.4776 - val_accuracy: 0.0809 - val_loss: 10.7942
Epoch 81/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 41s 55ms/step - accuracy: 0.6787 - loss: 1.4591 - val_accuracy: 0.0793 - val_loss: 10.8697
Epoch 82/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6822 - loss: 1.4434 - val_accuracy: 0.0817 - val_loss: 10.9129
Epoch 83/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6853 - loss: 1.4299 - val_accuracy: 0.0796 - val_loss: 10.9671
Epoch 84/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.6893 - loss: 1.4123 - val_accuracy: 0.0794 - val_loss: 11.0261
Epoch 85/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.6916 - loss: 1.3974 - val_accuracy: 0.0805 - val_loss: 11.0547
Epoch 86/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.6937 - loss: 1.3851 - val_accuracy: 0.0787 - val_loss: 11.1119
Epoch 87/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 35s 57ms/step - accuracy: 0.6978 - loss: 1.3682 - val_accuracy: 0.0793 - val_loss: 11.1595
Epoch 88/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 35s 57ms/step - accuracy: 0.7031 - loss: 1.3525 - val_accuracy: 0.0788 - val_loss: 11.1943
Epoch 89/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 41s 57ms/step - accuracy: 0.7046 - loss: 1.3390 - val_accuracy: 0.0774 - val_loss: 11.2471
Epoch 90/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 34s 55ms/step - accuracy: 0.7074 - loss: 1.3246 - val_accuracy: 0.0793 - val_loss: 11.3055
Epoch 91/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.7101 - loss: 1.3119 - val_accuracy: 0.0812 - val_loss: 11.3291
Epoch 92/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 41s 56ms/step - accuracy: 0.7139 - loss: 1.2960 - val_accuracy: 0.0768 - val_loss: 11.3917
Epoch 93/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.7157 - loss: 1.2845 - val_accuracy: 0.0788 - val_loss: 11.4335
Epoch 94/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.7197 - loss: 1.2684 - val_accuracy: 0.0768 - val_loss: 11.5089
Epoch 95/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 34s 55ms/step - accuracy: 0.7227 - loss: 1.2582 - val_accuracy: 0.0774 - val_loss: 11.5444
Epoch 96/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 42s 56ms/step - accuracy: 0.7263 - loss: 1.2435 - val_accuracy: 0.0764 - val_loss: 11.5744
Epoch 97/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 41s 56ms/step - accuracy: 0.7271 - loss: 1.2332 - val_accuracy: 0.0769 - val_loss: 11.6191
Epoch 98/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.7295 - loss: 1.2224 - val_accuracy: 0.0767 - val_loss: 11.6628
Epoch 99/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 34s 55ms/step - accuracy: 0.7331 - loss: 1.2088 - val_accuracy: 0.0765 - val_loss: 11.7274
Epoch 100/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.7362 - loss: 1.1969 - val_accuracy: 0.0748 - val_loss: 11.7651

In [40]:
lstm_model.save('lstm_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [41]:
index_to_word = {}
for word, index in word_index.items():
  index_to_word [index] = word

In [42]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [47]:
def predictor(model, tokenizer, text, max_len):
  text = text.lower()

  seq = tokenizer.texts_to_sequences([text])[0]
  seq = pad_sequences([seq], maxlen=max_len, padding='pre')
  pred = model.predict(seq, verbose=0)
  pred_index = np.argmax(pred)

  return index_to_word[pred_index]

In [57]:
seed_text = "why are you"
next_word = predictor(lstm_model, tokenizer, seed_text, max_len)
print(next_word)

worrying

In [60]:
def genrate_text(model, tokenizer, seed_text, max_len, n_words):
  for _ in range(n_words):
    next_word = predictor(model, tokenizer, seed_text, max_len)
    if next_word == "":
      break
    seed_text += " " + next_word
  return seed_text

In [67]:
seed  = "the meaning of life"
generated_text = genrate_text(lstm_model, tokenizer, seed, max_len, 10)
print(generated_text)

the meaning of life is not to love them when the heart will be

In [70]:
import pickle
with open ('tokenizer.pkl', 'wb') as f:
  pickle.dump(tokenizer, f)

In [71]:
with open("max_len.pkl", "wb") as f:
    pickle.dump(max_len, f)